GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sam_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sam_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO sam_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO sam_user;