server {
    listen 80;
    server_name 64.227.166.123;
    client_max_body_size 500M;

    location / {
        root /var/www/samanyudu/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # API Backend
    location /api/ {
        proxy_pass http://localhost:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Uploads directory
    location /uploads/ {
        alias /var/www/samanyudu/backend_api/uploads/;
        add_header Access-Control-Allow-Origin *;
    }

    # Mobile Web App
    location /mobile {
        alias /var/www/samanyudu/mobile_build/web;
        index index.html;
        try_files $uri $uri/ /mobile/index.html;
    }
}
